import { api, endpoints } from '../lib/api';

export interface Teacher {
    id: string;
    employee_code: string;
    first_name: string;
    last_name: string;
    email: string;
    phone?: string;
    hire_date: string;
    employment_type: string;
    department?: string;
    designation?: string;
    qualification?: string;
    years_experience?: number;
    is_active: boolean;
    branch_id: string;
    user_id?: string;
    user?: {
        employee_id?: string;
    };
    total_leaves?: number;
    used_leaves?: number;
}

export interface CreateTeacherDto {
    first_name: string;
    last_name: string;
    email: string;
    phone?: string;
    hire_date: string;
    employment_type: string;
    department?: string;
    designation?: string;
    qualification?: string;
    years_experience?: number;
    username?: string;
    password?: string;
    total_leaves?: number;
    used_leaves?: number;
}

export const teacherService = {
    async getAll() {
        const response = await api.get(endpoints.teachers.list);
        return response.data;
    },

    async getById(id: string) {
        const response = await api.get(endpoints.teachers.get(id));
        return response.data;
    },

    async create(data: CreateTeacherDto) {
        // Get branch_id from user in localStorage
        let branch_id: string | undefined;
        try {
            const userStr = localStorage.getItem('user');
            if (userStr) {
                const user = JSON.parse(userStr);
                branch_id = user?.branch_id || user?.branch?.id;
            }
        } catch (e) {
            console.error('Error parsing user from localStorage:', e);
        }

        // If still no branch_id, try to get from current_branch
        if (!branch_id) {
            try {
                const branchStr = localStorage.getItem('current_branch');
                if (branchStr) {
                    const branch = JSON.parse(branchStr);
                    branch_id = branch?.id;
                }
            } catch (e) {
                console.error('Error parsing current_branch from localStorage:', e);
            }
        }

        // If still no branch_id, fetch from API
        if (!branch_id) {
            try {
                const branchesResponse = await api.get(endpoints.branches.list);
                const branches = branchesResponse.data?.data || branchesResponse.data;
                if (branches && branches.length > 0) {
                    branch_id = branches[0].id;
                }
            } catch (e) {
                console.error('Error fetching branches:', e);
            }
        }

        // Transform frontend data to backend format
        const backendData = {
            ...data,
            // Auto-generate employee code (backend will validate uniqueness)
            // employee_code will be auto-generated by backend
            branch_id: branch_id,
            username: data.username,
            password: data.password,
        };

        const response = await api.post(endpoints.teachers.create, backendData);
        return response.data;
    },

    async update(id: string, data: Partial<CreateTeacherDto>) {
        const response = await api.put(endpoints.teachers.update(id), data);
        return response.data;
    },

    async delete(id: string) {
        const response = await api.delete(endpoints.teachers.delete(id));
        return response.data;
    },

    // ========== Teacher Portal Methods ==========

    /**
     * Get courses assigned to a specific teacher
     */
    async getCourses(teacherId: string) {
        const response = await api.get(endpoints.teachers.courses(teacherId));
        return response.data;
    },

    /**
     * Get all students in teacher's courses
     */
    async getStudents(teacherId: string) {
        // First get the teacher's courses, then count unique students
        const coursesResponse = await api.get(endpoints.teachers.courses(teacherId));
        const courses = coursesResponse.data?.data || coursesResponse.data || [];

        // Return courses with student count
        return courses.map((course: any) => ({
            ...course,
            studentCount: course.enrollments?.length || course.students?.length || 0
        }));
    },

    /**
     * Get attendance for a teacher
     */
    async getAttendance(teacherId: string, params?: { startDate?: string; endDate?: string }) {
        const response = await api.get(`/teachers/${teacherId}/attendance`, { params });
        return response.data;
    },

    // ========== Leave Management Methods ==========

    /**
     * Request leave for a teacher
     */
    async requestLeave(teacherId: string, data: {
        leaveType: 'annual' | 'sick' | 'casual';
        startDate: string;
        endDate: string;
        reason: string;
    }) {
        const response = await api.post('/leave/request', {
            teacherId,
            ...data,
        });
        return response.data;
    },

    /**
     * Get leave history for a teacher
     */
    async getLeaveHistory(teacherId: string, params?: { limit?: number; offset?: number; status?: string }) {
        const response = await api.get(`/leave/teacher/${teacherId}`, { params });
        return response.data;
    },

    /**
     * Get leave balance for a teacher
     */
    async getLeaveBalance(teacherId: string, year?: number) {
        const response = await api.get(`/leave/${teacherId}/balance`, { params: { year } });
        return response.data;
    },

    /**
     * Get all pending leave requests (Admin only)
     */
    async getPendingLeaves(params?: { limit?: number; offset?: number }) {
        const response = await api.get('/leave/pending', { params });
        return response.data;
    },

    /**
     * Approve a leave request (Admin only)
     */
    async approveLeave(leaveRequestId: string) {
        const response = await api.post(`/leave/${leaveRequestId}/approve`);
        return response.data;
    },

    /**
     * Reject a leave request (Admin only)
     */
    async rejectLeave(leaveRequestId: string, reason?: string) {
        const response = await api.post(`/leave/${leaveRequestId}/reject`, { reason });
        return response.data;
    },
};
